include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "build/**"
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    prefer_single_quotes: true
    always_declare_return_types: true
    avoid_print: true
    cancel_subscriptions: true
    close_sinks: true
    prefer_final_locals: true
    prefer_const_constructors: true
    unawaited_futures: true
    directives_ordering: true
    require_trailing_commas: true
